<?php

namespace TchatBundle\Repository;

/**
 * RoomUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomUserRepository extends \Doctrine\ORM\EntityRepository
{
}
